env:
  es6: true
  browser: true
  commonjs: true

extends: ['plugin:react/recommended']

parserOptions:
  sourceType: "module"
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true

plugins: ['react']

settings:
  react:
    version: '16'
